// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// wk.cpp
sexp cpp_bbox_handler_new();
extern "C" SEXP _wkmike_cpp_bbox_handler_new() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_bbox_handler_new());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_wkmike_cpp_bbox_handler_new", (DL_FUNC) &_wkmike_cpp_bbox_handler_new, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_wkmike(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
