# Generated by cpp11: do not edit by hand

cpp_handle_xy <- function(input, handler_xptr) {
  .Call(`_wkmike_cpp_handle_xy`, input, handler_xptr)
}

cpp_bbox_handler_new <- function() {
  .Call(`_wkmike_cpp_bbox_handler_new`)
}
